
import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font, Image } from '@react-pdf/renderer';
import { Invoice, Organization, Client, InvoiceItem, BankDetail, InvoiceTemplate } from '@prisma/client';

// Register font for Czech characters and other scripts (Azbuka, Chinese)
// Using Noto Sans as a fallback for broader unicode support if possible, or sticking to Roboto which covers Cyrillic.
// Note: Standard Roboto doesn't cover Chinese. For Chinese, we'd need a font like Noto Sans SC.
// Since we can't easily download 30MB font files here, we will register a font that is known to have good coverage 
// or at least Cyrillic (Roboto usually has it). 
// For Chinese in react-pdf, we typically need to register a specific font. 
// We will register Noto Sans from a CDN if available, or just stick with Roboto for now as it covers Azbuka.
// Ideally for Chinese: https://fonts.gstatic.com/s/notosanssc/v12/k3kXo84MPvpLmixcA63OEALhLOCT-xWtm9i3.woff2 (but woff2 not supported by all react-pdf versions, ttf preferred)

Font.register({
  family: 'Roboto',
  fonts: [
    { src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf', fontWeight: 300 },
    { src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-regular-webfont.ttf', fontWeight: 400 },
    { src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-medium-webfont.ttf', fontWeight: 500 },
    { src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-bold-webfont.ttf', fontWeight: 700 },
  ],
});

// Explicitly register 'Roboto-Bold' alias if used directly in styles
Font.register({
  family: 'Roboto-Bold',
  src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-bold-webfont.ttf'
});

// Fallback font for Chinese (Simulated registration - in real app would need actual TTF url)
Font.register({
  family: 'NotoSansSC',
  src: 'https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-sc@5.0.12/files/noto-sans-sc-chinese-simplified-400-normal.woff' 
});

const translations = {
  cs: {
    invoice: "Faktura",
    proforma: "Zálohová faktura",
    advance: "Zálohový list",
    quotation: "Cenová nabídka",
    correction: "Opravný daňový doklad",
    deliveryNote: "Dodací list",
    number: "číslo",
    relatedId: "K dokladu ID",
    supplier: "Dodavatel",
    subscriber: "Odběratel",
    taxId: "IČ",
    vatId: "DIČ",
    bankAccount: "Bankovní spojení",
    vatPayer: "Plátce DPH",
    identifiedPerson: "Identifikovaná osoba",
    yes: "ANO",
    no: "NE",
    issuedAt: "Datum vystavení",
    dueAt: "Datum splatnosti",
    varSymbol: "Variabilní symbol",
    taxDate: "DUZP",
    item: "Položka",
    qty: "Mn.",
    pricePerUnit: "Cena/j",
    discount: "Sleva",
    vat: "DPH",
    total: "Celkem",
    docDiscount: "Sleva na doklad",
    totalNoVat: "Celkem bez DPH",
    totalPayable: "K úhradě",
    reverseCharge: "Daň odvede zákazník (Režim přenesení daňové povinnosti / Reverse Charge).",
    oss: "Daň odváděna v režimu OSS.",
    identifiedPersonNote: "Osoba identifikovaná k dani. Daň odvede zákazník (pokud jde o službu do EU).",
    vatRecap: "Rekapitulace DPH",
    vatRecapCzk: "Rekapitulace DPH v CZK",
    rate: "Sazba DPH",
    base: "Základ",
    qrPayment: "QR Platba",
    footer: "Vystaveno v systému Vulpi • Děkujeme za spolupráci",
    unpaid: "NEUHRAZENO",
    page: "Strana",
    of: "z"
  },
  en: {
    invoice: "Invoice",
    proforma: "Proforma Invoice",
    advance: "Advance Invoice",
    quotation: "Quotation",
    correction: "Credit Note",
    deliveryNote: "Delivery Note",
    number: "No.",
    relatedId: "Ref. ID",
    supplier: "Supplier",
    subscriber: "Customer",
    taxId: "Reg. No.",
    vatId: "VAT ID",
    bankAccount: "Bank Account",
    vatPayer: "VAT Payer",
    identifiedPerson: "Identified Person",
    yes: "YES",
    no: "NO",
    issuedAt: "Issue Date",
    dueAt: "Due Date",
    varSymbol: "Variable Symbol",
    taxDate: "Tax Date",
    item: "Item",
    qty: "Qty",
    pricePerUnit: "Unit Price",
    discount: "Disc.",
    vat: "VAT",
    total: "Total",
    docDiscount: "Discount",
    totalNoVat: "Total excl. VAT",
    totalPayable: "Total Payable",
    reverseCharge: "Reverse Charge - VAT to be accounted for by the recipient.",
    oss: "VAT accounted for under OSS scheme.",
    identifiedPersonNote: "Identified Person. VAT to be accounted for by the recipient (for EU services).",
    vatRecap: "VAT Recap",
    vatRecapCzk: "VAT Recap in CZK",
    rate: "VAT Rate",
    base: "Base",
    qrPayment: "QR Payment",
    footer: "Generated by Vulpi • Thank you for your business",
    unpaid: "UNPAID",
    page: "Page",
    of: "of"
  },
  de: {
    invoice: "Rechnung",
    proforma: "Proforma-Rechnung",
    advance: "Anzahlungsrechnung",
    quotation: "Angebot",
    correction: "Gutschrift",
    deliveryNote: "Lieferschein",
    number: "Nr.",
    relatedId: "Ref. ID",
    supplier: "Lieferant",
    subscriber: "Kunde",
    taxId: "Steuernummer",
    vatId: "USt-IdNr.",
    bankAccount: "Bankverbindung",
    vatPayer: "USt-Zahler",
    identifiedPerson: "Identifizierte Person",
    yes: "JA",
    no: "NEIN",
    issuedAt: "Ausstellungsdatum",
    dueAt: "Fälligkeitsdatum",
    varSymbol: "Verwendungszweck",
    taxDate: "Leistungsdatum",
    item: "Artikel",
    qty: "Menge",
    pricePerUnit: "Einzelpreis",
    discount: "Rabatt",
    vat: "MwSt",
    total: "Gesamt",
    docDiscount: "Rabatt",
    totalNoVat: "Gesamt ohne MwSt",
    totalPayable: "Zahlungsbetrag",
    reverseCharge: "Steuerschuldnerschaft des Leistungsempfängers (Reverse Charge).",
    oss: "Besteuerung nach OSS.",
    identifiedPersonNote: "Identifizierte Person. Steuerschuldnerschaft des Leistungsempfängers (bei EU-Dienstleistungen).",
    vatRecap: "MwSt-Zusammenfassung",
    vatRecapCzk: "MwSt-Zusammenfassung in CZK",
    rate: "MwSt-Satz",
    base: "Basis",
    qrPayment: "QR-Zahlung",
    footer: "Erstellt mit Vulpi • Vielen Dank für die Zusammenarbeit",
    unpaid: "UNBEZAHLT",
    page: "Seite",
    of: "von"
  },
  sk: {
    invoice: "Faktúra",
    proforma: "Zálohová faktúra",
    advance: "Zálohový list",
    quotation: "Cenová ponuka",
    correction: "Dobropis",
    deliveryNote: "Dodací list",
    number: "číslo",
    relatedId: "K dokladu ID",
    supplier: "Dodávateľ",
    subscriber: "Odberateľ",
    taxId: "IČO",
    vatId: "IČ DPH",
    bankAccount: "Bankové spojenie",
    vatPayer: "Platca DPH",
    identifiedPerson: "Identifikovaná osoba",
    yes: "ÁNO",
    no: "NIE",
    issuedAt: "Dátum vystavenia",
    dueAt: "Dátum splatnosti",
    varSymbol: "Variabilný symbol",
    taxDate: "Dátum dodania",
    item: "Položka",
    qty: "Mn.",
    pricePerUnit: "Cena/j",
    discount: "Zľava",
    vat: "DPH",
    total: "Celkom",
    docDiscount: "Zľava na doklad",
    totalNoVat: "Celkom bez DPH",
    totalPayable: "K úhrade",
    reverseCharge: "Daň odvedie zákazník (Prenesenie daňovej povinnosti / Reverse Charge).",
    oss: "Daň odvádzaná v režime OSS.",
    identifiedPersonNote: "Osoba identifikovaná pre daň. Daň odvedie zákazník (ak ide o službu do EÚ).",
    vatRecap: "Rekapitulácia DPH",
    vatRecapCzk: "Rekapitulácia DPH v CZK",
    rate: "Sadzba DPH",
    base: "Základ",
    qrPayment: "QR Platba",
    footer: "Vystavené v systéme Vulpi • Ďakujeme za spoluprácu",
    unpaid: "NEUHRADENÉ",
    page: "Strana",
    of: "z"
  }
};

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Roboto', // Default
    fontSize: 10,
    padding: 30,
    flexDirection: 'column',
  },
  // Add a specific class if we detect Chinese content or allow mixing?
  // React-pdf handles font fallback if registered in family array, but we registered separate families.
  // We can try to use a font family stack if supported, but react-pdf 2.0+ supports it better.
  // For now, let's keep Roboto as main.
  
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontFamily: 'Roboto-Bold',
    color: '#111',
  },
  subtitle: {
    fontSize: 10,
    color: '#666',
    marginTop: 4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    flexDirection: 'column',
    width: '48%',
  },
  label: {
    fontSize: 8,
    color: '#666',
    marginBottom: 2,
  },
  value: {
    fontSize: 10,
    marginBottom: 8,
  },
  bold: {
    fontFamily: 'Roboto-Bold',
  },
  table: {
    marginTop: 20,
    marginBottom: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 4,
    marginBottom: 4,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingTop: 4,
    paddingBottom: 4,
  },
  colDesc: { width: '35%' },
  colQty: { width: '10%', textAlign: 'right' },
  colUnit: { width: '15%', textAlign: 'right' },
  colDisc: { width: '10%', textAlign: 'right' },
  colVat: { width: '10%', textAlign: 'right' },
  colTotal: { width: '20%', textAlign: 'right' },
  
  totalSection: {
    marginTop: 10,
    alignItems: 'flex-end',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 4,
  },
  totalLabel: {
    width: 120,
    textAlign: 'right',
    paddingRight: 10,
  },
  totalValue: {
    width: 100,
    textAlign: 'right',
    fontFamily: 'Roboto-Bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 8,
    color: '#aaa',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 10,
  },
  qrCode: {
    width: 100,
    height: 100,
    marginTop: 10,
  },
  qrSection: {
    marginTop: 20,
    alignItems: 'flex-start',
  },
  watermark: {
    position: 'absolute',
    top: 300,
    left: 100,
    transform: 'rotate(-45deg)',
    fontSize: 60,
    color: '#ff0000',
    opacity: 0.1,
    width: 400,
    textAlign: 'center',
  },
  recapTable: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 10,
  },
  recapRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    fontSize: 8,
    color: '#666',
  }
});

interface InvoicePDFProps {
  invoice: Invoice & {
    organization: Organization;
    client: Client;
    items: InvoiceItem[];
    bankDetail: BankDetail | null;
    template: InvoiceTemplate | null;
  };
  qrCodeUrl?: string;
  barcodes?: Record<string, string>; // Map of itemId -> base64 barcode image
}

const formatDate = (date: Date, locale: string = 'cs-CZ') => {
  return new Date(date).toLocaleDateString(locale);
};

const formatCurrency = (amount: number, currency: string, locale: string = 'cs-CZ') => {
  return new Intl.NumberFormat(locale, { style: 'currency', currency }).format(amount);
};

export const InvoicePage = ({ invoice, qrCodeUrl, barcodes }: InvoicePDFProps) => {
  const isVatPayer = invoice.vatMode !== 'NON_PAYER' && invoice.vatMode !== 'IDENTIFIED_PERSON';
  const isReverseCharge = invoice.vatMode === 'REVERSE_CHARGE';
  const isOSS = invoice.vatMode === 'OSS';
  const isIdentifiedPerson = invoice.vatMode === 'IDENTIFIED_PERSON';
  const isForeignCurrency = invoice.currency !== 'CZK';
  const exchangeRate = invoice.exchangeRate || 1;
  const isOverdue = invoice.status !== 'PAID' && invoice.status !== 'CANCELLED' && new Date(invoice.dueAt) < new Date();
  const showBarcodes = invoice.template?.showBarcodes ?? false;
  
  const langCode = (invoice.client.language as keyof typeof translations) || 'cs';
  const baseTranslations = translations[langCode];

  // 1. Text Overrides
  let t = { ...baseTranslations };
  // @ts-ignore
  if (invoice.template?.textOverrides) {
    try {
      // @ts-ignore
      const overrides = JSON.parse(invoice.template.textOverrides);
      t = { ...t, ...overrides };
    } catch (e) {
      console.error("Failed to parse text overrides", e);
    }
  }

  const getLocale = (lang: string) => {
    switch (lang) {
      case 'en': return 'en-GB';
      case 'de': return 'de-DE';
      case 'sk': return 'sk-SK';
      default: return 'cs-CZ';
    }
  };
  
  const locale = getLocale(langCode);

  // 2. Dynamic Styles
  const primaryColor = invoice.template?.primaryColor || '#000000';
  const secondaryColor = invoice.template?.secondaryColor || '#666666';
  // fontFamily is tricky with @react-pdf as fonts must be registered. 
  // We'll skip dynamic font registration for now to avoid crashes, 
  // but we could map 'Roboto' variants if we had them.

  const dynamicStyles = StyleSheet.create({
    title: {
      color: primaryColor,
    },
    tableHeader: {
      borderBottomColor: primaryColor,
    },
    totalValue: {
      color: primaryColor,
    },
    headerRight: {
      alignItems: 'flex-end',
    },
    headerLeft: {
      alignItems: 'flex-start',
    },
    headerCenter: {
      alignItems: 'center',
      width: '100%',
    },
    subtitle: {
      color: secondaryColor,
    },
    label: {
      color: secondaryColor,
    }
  });

  // 3. Logo Position Logic
  const logoPosition = invoice.template?.logoPosition || 'left';
  const showQrCode = invoice.template?.showQrCode ?? true;
  const showSignature = invoice.template?.showSignature ?? true;

  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString(locale);
  };
  
  const formatCurrency = (amount: number, currency: string) => {
    return new Intl.NumberFormat(locale, { style: 'currency', currency }).format(amount);
  };

  // Document Title
  let title = t.invoice;
  if (invoice.type === 'PROFORMA') title = t.proforma;
  else if (invoice.type === 'ZALOHOVY_LIST') title = t.advance;
  else if (invoice.type === 'NABIDKA') title = t.quotation;
  else if (invoice.type === 'DOBROPIS') title = t.correction;
  else if (invoice.type === 'DODACI_LIST') title = t.deliveryNote;

  // Calculate Discounts
  const hasItemDiscounts = invoice.items.some((i: any) => i.discount > 0);
  const docDiscountPct = invoice.discount || 0;

  // VAT Recapitulation Logic
  // Group by VAT rate
  const vatGroups = invoice.items.reduce((acc: any, item: any) => {
    const rate = item.vatRate;
    if (!acc[rate]) acc[rate] = { base: 0, vat: 0 };
    
    // item.totalAmount is the line total (discounted unit price * qty)
    // We need to apply document discount to this base for accurate VAT calc in recap
    const baseAmount = item.totalAmount * (1 - docDiscountPct / 100);
    
    acc[rate].base += baseAmount;
    if (!isReverseCharge && isVatPayer) {
       // Recalculate VAT from the discounted base
       acc[rate].vat += baseAmount * (rate / 100);
    }
    return acc;
  }, {} as Record<number, { base: number; vat: number }>);

  return (
      <Page size="A4" style={styles.page}>
        {isOverdue && (
            <View style={styles.watermark}>
                <Text>{t.unpaid}</Text>
            </View>
        )}

        {/* Header */}
        <View style={[styles.header, logoPosition === 'center' ? { flexDirection: 'column', alignItems: 'center' } : { flexDirection: 'row', justifyContent: 'space-between' }]}>
            
            {/* Left Column (or Top if Center) */}
            {logoPosition === 'left' ? (
                // Logo on Left
                <View>
                   {invoice.organization.logoUrl ? (
                       <Image src={invoice.organization.logoUrl} style={{ width: 100, height: 50, objectFit: 'contain' }} />
                   ) : (
                       <Text style={[styles.title, { fontSize: 16 }]}>{invoice.organization.name}</Text>
                   )}
                </View>
            ) : logoPosition === 'right' ? (
                // Document Info on Left
                <View>
                    <Text style={[styles.title, dynamicStyles.title]}>{title}</Text>
                    <Text style={styles.subtitle}>{t.number}: {invoice.number}</Text>
                     {invoice.relatedId && (
                        <Text style={[styles.subtitle, { fontSize: 8 }]}>{t.relatedId}: {invoice.relatedId}</Text>
                    )}
                </View>
            ) : (
                // Center - Logo Top
                <View style={{ alignItems: 'center', marginBottom: 10 }}>
                     {invoice.organization.logoUrl ? (
                       <Image src={invoice.organization.logoUrl} style={{ width: 100, height: 50, objectFit: 'contain' }} />
                   ) : (
                       <Text style={[styles.title, { fontSize: 16 }]}>{invoice.organization.name}</Text>
                   )}
                </View>
            )}

            {/* Right Column (or Bottom if Center) */}
            {logoPosition === 'left' ? (
                // Document Info on Right
                 <View style={{ alignItems: 'flex-end' }}>
                    <Text style={[styles.title, dynamicStyles.title]}>{title}</Text>
                    <Text style={styles.subtitle}>{t.number}: {invoice.number}</Text>
                     {invoice.relatedId && (
                        <Text style={[styles.subtitle, { fontSize: 8 }]}>{t.relatedId}: {invoice.relatedId}</Text>
                    )}
                </View>
            ) : logoPosition === 'right' ? (
                // Logo on Right
                <View style={{ alignItems: 'flex-end' }}>
                   {invoice.organization.logoUrl ? (
                       <Image src={invoice.organization.logoUrl} style={{ width: 100, height: 50, objectFit: 'contain' }} />
                   ) : (
                       <Text style={[styles.title, { fontSize: 16 }]}>{invoice.organization.name}</Text>
                   )}
                </View>
            ) : (
                // Center - Document Info Bottom
                <View style={{ alignItems: 'center' }}>
                    <Text style={[styles.title, dynamicStyles.title]}>{title}</Text>
                    <Text style={styles.subtitle}>{t.number}: {invoice.number}</Text>
                     {invoice.relatedId && (
                        <Text style={[styles.subtitle, { fontSize: 8 }]}>{t.relatedId}: {invoice.relatedId}</Text>
                    )}
                </View>
            )}
        </View>

        {/* Supplier & Subscriber */}
        <View style={styles.row}>
          <View style={styles.column}>
            <Text style={[styles.label, styles.bold, { marginBottom: 6, fontSize: 12 }]}>{t.supplier}</Text>
            <Text style={[styles.value, styles.bold]}>{invoice.organization.name}</Text>
            <Text style={styles.value}>{invoice.organization.address}</Text>
            
            <View style={{ marginTop: 8 }}>
              <Text style={styles.value}>{t.taxId}: {invoice.organization.taxId}</Text>
              {invoice.organization.vatId && <Text style={styles.value}>{t.vatId}: {invoice.organization.vatId}</Text>}
            </View>

            {invoice.bankDetail && (
              <View style={{ marginTop: 8 }}>
                <Text style={styles.label}>{t.bankAccount}:</Text>
                <Text style={styles.value}>{invoice.bankDetail.accountNumber}</Text>
                <Text style={styles.value}>{invoice.bankDetail.bankName}</Text>
                {invoice.bankDetail.iban && <Text style={styles.value}>IBAN: {invoice.bankDetail.iban}</Text>}
                {invoice.bankDetail.swift && <Text style={styles.value}>SWIFT: {invoice.bankDetail.swift}</Text>}
              </View>
            )}
            
            <View style={{ marginTop: 8 }}>
                <Text style={styles.label}>{t.vatPayer}:</Text>
                <Text style={styles.value}>
                  {invoice.vatMode === 'IDENTIFIED_PERSON' ? t.identifiedPerson : (isVatPayer ? t.yes : t.no)}
                </Text>
            </View>
          </View>

          <View style={styles.column}>
            <Text style={[styles.label, styles.bold, { marginBottom: 6, fontSize: 12 }]}>{t.subscriber}</Text>
            <Text style={[styles.value, styles.bold]}>{invoice.client.name}</Text>
            <Text style={styles.value}>{invoice.client.address}</Text>

            <View style={{ marginTop: 8 }}>
              {invoice.client.taxId && <Text style={styles.value}>{t.taxId}: {invoice.client.taxId}</Text>}
              {invoice.client.vatId && <Text style={styles.value}>{t.vatId}: {invoice.client.vatId}</Text>}
            </View>

            <View style={{ marginTop: 20, padding: 10, backgroundColor: '#f9f9f9', borderRadius: 4 }}>
              <View style={styles.row}>
                <View>
                  <Text style={styles.label}>{t.issuedAt}:</Text>
                  <Text style={styles.value}>{formatDate(invoice.issuedAt)}</Text>
                </View>
                <View>
                  <Text style={styles.label}>{t.dueAt}:</Text>
                  <Text style={styles.value}>{formatDate(invoice.dueAt)}</Text>
                </View>
              </View>
              <View style={{ marginTop: 8 }}>
                <Text style={styles.label}>{t.varSymbol}:</Text>
                <Text style={styles.value}>{invoice.variableSymbol || '-'}</Text>
              </View>
              {isVatPayer && (
                 <View style={{ marginTop: 8 }}>
                    <Text style={styles.label}>{t.taxDate}:</Text>
                    <Text style={styles.value}>{formatDate(invoice.issuedAt)}</Text>
                 </View>
              )}
            </View>
          </View>
        </View>

        {/* Items Table */}
        <View style={styles.table}>
          <View style={[styles.tableHeader, dynamicStyles.tableHeader]}>
            {showBarcodes && <Text style={[styles.bold, { width: '10%' }]}>SKU</Text>}
            <Text style={[styles.colDesc, styles.bold, showBarcodes ? { width: '25%' } : {}]}>{t.item}</Text>
            <Text style={[styles.colQty, styles.bold]}>{t.qty}</Text>
            <Text style={[styles.colUnit, styles.bold]}>{t.pricePerUnit}</Text>
            <Text style={[styles.colDisc, styles.bold]}>{t.discount}</Text>
            {isVatPayer && <Text style={[styles.colVat, styles.bold]}>{t.vat}</Text>}
            <Text style={[styles.colTotal, styles.bold]}>{t.total}</Text>
          </View>
          {invoice.items.map((item: any, index: number) => (
            <View key={index} style={[styles.tableRow]}>
              {showBarcodes && (
                <View style={{ width: '10%' }}>
                  <Text style={{ fontSize: 8 }}>{item.sku || '-'}</Text>
                </View>
              )}
              <View style={[styles.colDesc, showBarcodes ? { width: '25%' } : {}]}>
                <Text>{item.description}</Text>
                {showBarcodes && barcodes && barcodes[item.id] && (
                  <Image 
                    src={barcodes[item.id]} 
                    style={{ width: 100, height: 20, marginTop: 2, objectFit: 'contain' }} 
                  />
                )}
              </View>
              <Text style={styles.colQty}>{item.quantity}</Text>
              <Text style={styles.colUnit}>{formatCurrency(item.unitPrice, invoice.currency)}</Text>
              <Text style={styles.colDisc}>{item.discount > 0 ? `${item.discount} %` : '-'}</Text>
              {isVatPayer && <Text style={styles.colVat}>{item.vatRate}%</Text>}
              <Text style={styles.colTotal}>{formatCurrency(item.totalAmount, invoice.currency)}</Text>
            </View>
          ))}
        </View>

        {/* Totals */}
        <View style={styles.totalSection}>
          {docDiscountPct > 0 && (
             <View style={styles.totalRow}>
               <Text style={styles.totalLabel}>{t.docDiscount}:</Text>
               <Text style={styles.totalValue}>{docDiscountPct} %</Text>
             </View>
          )}
          
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>{t.totalNoVat}:</Text>
            {/* Base is Total Amount - Total VAT. Wait, invoice.totalAmount includes VAT. */}
            <Text style={styles.totalValue}>{formatCurrency(invoice.totalAmount - invoice.totalVat, invoice.currency)}</Text>
          </View>
          
          {isVatPayer && (
            <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>{t.vat}:</Text>
                <Text style={styles.totalValue}>{formatCurrency(invoice.totalVat, invoice.currency)}</Text>
            </View>
          )}
          
          <View style={[styles.totalRow, { marginTop: 4, borderTopWidth: 1, borderTopColor: '#000', paddingTop: 4 }]}>
            <Text style={[styles.totalLabel, styles.bold, { fontSize: 12 }]}>{t.totalPayable}:</Text>
            <Text style={[styles.totalValue, styles.bold, { fontSize: 12 }]}>{formatCurrency(invoice.totalAmount, invoice.currency)}</Text>
          </View>
        </View>
        
        {/* Reverse Charge Note */}
        {isReverseCharge && (
            <View style={{ marginTop: 10, padding: 5, border: '1px solid #ccc' }}>
                <Text style={{ fontSize: 9 }}>{t.reverseCharge}</Text>
            </View>
        )}
        
        {/* OSS Note */}
        {isOSS && (
            <View style={{ marginTop: 10, padding: 5, border: '1px solid #ccc' }}>
                <Text style={{ fontSize: 9 }}>{t.oss}</Text>
            </View>
        )}

        {/* Identified Person Note */}
        {isIdentifiedPerson && (
            <View style={{ marginTop: 10, padding: 5, border: '1px solid #ccc' }}>
                <Text style={{ fontSize: 9 }}>{t.identifiedPersonNote}</Text>
            </View>
        )}

        {/* VAT Recapitulation (Invoice Currency) */}
        {isVatPayer && (
            <View style={styles.recapTable}>
                <Text style={[styles.bold, { fontSize: 9, marginBottom: 5 }]}>{t.vatRecap} ({invoice.currency})</Text>
                <View style={[styles.row, { borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 2 }]}>
                    <Text style={{ width: '20%', fontSize: 8 }}>{t.rate}</Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{t.base}</Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{t.vat}</Text>
                    <Text style={{ width: '20%', fontSize: 8, textAlign: 'right' }}>{t.total}</Text>
                </View>
                {(Object.entries(vatGroups) as any[]).map(([rate, { base, vat }]: [string, { base: number; vat: number }]) => (
                    <View key={rate} style={styles.row}>
                        <Text style={{ width: '20%', fontSize: 8 }}>{rate} %</Text>
                        <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{formatCurrency(base, invoice.currency)}</Text>
                        <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{formatCurrency(vat, invoice.currency)}</Text>
                        <Text style={{ width: '20%', fontSize: 8, textAlign: 'right' }}>{formatCurrency(base + vat, invoice.currency)}</Text>
                    </View>
                ))}
                <View style={[styles.row, { borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 2 }]}>
                    <Text style={{ width: '20%', fontSize: 8, fontFamily: 'Roboto-Bold' }}>{t.total}</Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>
                        {formatCurrency((Object.values(vatGroups) as any[]).reduce((sum: number, g: { base: number; vat: number }) => sum + g.base, 0), invoice.currency)}
                    </Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>
                        {formatCurrency((Object.values(vatGroups) as any[]).reduce((sum: number, g: { base: number; vat: number }) => sum + g.vat, 0), invoice.currency)}
                    </Text>
                    <Text style={{ width: '20%', fontSize: 8, textAlign: 'right' }}>
                        {formatCurrency((Object.values(vatGroups) as any[]).reduce((sum: number, g: { base: number; vat: number }) => sum + g.base + g.vat, 0), invoice.currency)}
                    </Text>
                </View>
            </View>
        )}

        {/* VAT Recapitulation (CZK) for Foreign Currency */}
        {isForeignCurrency && isVatPayer && (
            <View style={styles.recapTable}>
                <Text style={[styles.bold, { fontSize: 9, marginBottom: 5 }]}>{t.vatRecapCzk} (Kurz ČNB: {exchangeRate.toFixed(3)} CZK/{invoice.currency})</Text>
                <View style={[styles.row, { borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 2 }]}>
                    <Text style={{ width: '20%', fontSize: 8 }}>{t.rate}</Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{t.base} (CZK)</Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{t.vat} (CZK)</Text>
                    <Text style={{ width: '20%', fontSize: 8, textAlign: 'right' }}>{t.total} (CZK)</Text>
                </View>
                {(Object.entries(vatGroups) as any[]).map(([rate, { base, vat }]: [string, { base: number; vat: number }]) => (
                    <View key={rate} style={styles.row}>
                        <Text style={{ width: '20%', fontSize: 8 }}>{rate} %</Text>
                        <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{formatCurrency(base * exchangeRate, 'CZK')}</Text>
                        <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>{formatCurrency(vat * exchangeRate, 'CZK')}</Text>
                        <Text style={{ width: '20%', fontSize: 8, textAlign: 'right' }}>{formatCurrency((base + vat) * exchangeRate, 'CZK')}</Text>
                    </View>
                ))}
                <View style={[styles.row, { borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 2 }]}>
                    <Text style={{ width: '20%', fontSize: 8, fontFamily: 'Roboto-Bold' }}>{t.total}</Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>
                        {formatCurrency((Object.values(vatGroups) as any[]).reduce((sum, g) => sum + g.base, 0) * exchangeRate, 'CZK')}
                    </Text>
                    <Text style={{ width: '30%', fontSize: 8, textAlign: 'right' }}>
                        {formatCurrency((Object.values(vatGroups) as any[]).reduce((sum, g) => sum + g.vat, 0) * exchangeRate, 'CZK')}
                    </Text>
                    <Text style={{ width: '20%', fontSize: 8, textAlign: 'right' }}>
                        {formatCurrency((Object.values(vatGroups) as any[]).reduce((sum, g) => sum + g.base + g.vat, 0) * exchangeRate, 'CZK')}
                    </Text>
                </View>
            </View>
        )}

        {/* QR Code */}
        {qrCodeUrl && showQrCode && (
          <View style={styles.qrSection}>
            <Text style={styles.label}>{t.qrPayment}</Text>
            {/* eslint-disable-next-line jsx-a11y/alt-text */}
            <Image style={styles.qrCode} src={qrCodeUrl} />
          </View>
        )}

        {/* Signature & Stamp */}
        {showSignature && (
          <View style={{ marginTop: 30, alignItems: 'flex-end', marginRight: 30 }}>
            {invoice.organization.logoUrl ? (
               <View style={{ alignItems: 'center', marginBottom: 5 }}>
                  <Image src={invoice.organization.logoUrl} style={{ width: 100, height: 50, objectFit: 'contain' }} />
               </View>
            ) : (
               <View style={{ width: 150, height: 50 }} /> // Spacer if no stamp
            )}
            <View style={{ width: 150, borderBottomWidth: 1, borderBottomColor: '#000', marginBottom: 5 }} />
            <Text style={{ fontSize: 8 }}>Razítko a podpis</Text>
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>{t.footer}</Text>
        </View>
      </Page>
  );
};

export const InvoicePDF = (props: InvoicePDFProps) => (
  <Document>
    <InvoicePage {...props} />
  </Document>
);
